{!! BootForm::text(trans('users::global.attributes.contact_name'), 'contact_name') !!}
{!! BootForm::text(trans('users::global.attributes.phone'), 'phone') !!}
{!! BootForm::text(trans('users::global.attributes.address'), 'address') !!}
{!! BootForm::text(trans('users::global.attributes.address2'), 'address2') !!}
{!! BootForm::text(trans('users::global.attributes.postcode'), 'postcode') !!}
{!! BootForm::text(trans('users::global.attributes.city'), 'city') !!}
{!! BootForm::text(trans('users::global.attributes.state'), 'state') !!}
{!! BootForm::text(trans('users::global.attributes.country'), 'country') !!}
{!! BootForm::text(trans('users::global.attributes.details'), 'details') !!}
{!! BootForm::submit(trans('users::global.save'))->class('btn btn-primary') !!}